use aurak

SET XACT_ABORT ON
BEGIN TRAN

DECLARE @TABLE TABLE (id int, mail nvarchar(max))

INSERT INTO [user]
(FirstName, LastName, Username, Email, EmailVerified, Active, ClientId, LastActivity, CreationTime)
output inserted.Id, inserted.Email INTO @TABLE
VALUES
('Abdelfatah', 'Said  Arman', 'abdelfatah.arman@aurak.ac.ae', 'abdelfatah.arman@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Abdul', 'Rahman  Hisham M.  Al Muaitah', 'abdul.almuaitah@aurak.ac.ae', 'abdul.almuaitah@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Abeer', 'Abdulla Esmaeel Al Malki Al Harmi', 'abeer.almalki@aurak.ac.ae', 'abeer.almalki@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Abeer', 'Shaher Abu Raed', 'abeer.raed@aurak.ac.ae', 'abeer.raed@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Ahmad', 'Hasan Ismail Sakhrieh', 'ahmad.sakhrieh@aurak.ac.ae', 'ahmad.sakhrieh@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Ahmad', 'Ismail Anaqweh', 't.ahmedanaqweh@aurak.ac.ae', 't.ahmedanaqweh@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Aisha', 'Murad  Abo Rebea', 'aisha.rebea@aurak.ac.ae', 'aisha.rebea@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Alexandria', 'Alisa  Proff', 'alexandria.proff@aurak.ac.ae', 'alexandria.proff@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Ali', 'Abdulnaser Saud Alnoman', 'ali.alnoman@aurak.ac.ae', 'ali.alnoman@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Ali', 'Al Ataby', 'ali.ataby@aurak.ac.ae', 'ali.ataby@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Alvin', 'Bajamunde Lumbao', 'alvin.lumbao@aurak.ac.ae', 'alvin.lumbao@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Amanda Fiona', 'Forte', 'amanda.forte@aurak.ac.ae', 'amanda.forte@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Amna', 'Younas', 'amna.younas@aurak.ac.ae', 'amna.younas@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Anis', 'Semlali', 'anis.semlali@aurak.ac.ae', 'anis.semlali@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Arfan', 'Ghani', 'arfan.ghani@aurak.ac.ae', 'arfan.ghani@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Arnold Galang', 'Uaje', 'arnold.uaje@aurak.ac.ae', 'arnold.uaje@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Asha Caroline', 'Cyril', 't.ashacyril@aurak.ac.ae', 't.ashacyril@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Babatunde', 'Opeyemi Alamurin', 'babatunde.alamurin@aurak.ac.ae', 'babatunde.alamurin@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Baliira', 'Kalyebara', 'baliira.kalyebara@aurak.ac.ae', 'baliira.kalyebara@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Basem', 'Yousef', 'basem.yousef@aurak.ac.ae', 'basem.yousef@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Beza', 'Getu', 'bgetu@aurak.ac.ae', 'bgetu@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Bong-Sik', 'Kim', 'bkim@aurak.ac.ae', 'bkim@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Bryn', 'Holmes', 'bryn.holmes@aurak.ac.ae', 'bryn.holmes@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Busher', 'Idris', 'busher.idris@aurak.ac.ae', 'busher.idris@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Buthayna', 'Hasan Mohammad Eilouti', 'buthayna.eilouti@aurak.ac.ae', 'buthayna.eilouti@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Carolyn', 'Escobido Ricaplaza', 'carolyn.ricaplaza@aurak.ac.ae', 'carolyn.ricaplaza@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Cijo', 'George Vazhappilly', 'cijo.vazhappilly@aurak.ac.ae', 'cijo.vazhappilly@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Cristiano', 'Luchetti', 'cristiano.luchetti@aurak.ac.ae', 'cristiano.luchetti@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Danilo', 'Cruz Sangil', 'danilo.sangil@aurak.ac.ae', 'danilo.sangil@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Dina', 'Hemdan Elsayed Antar', 'dina.antar@aurak.ac.ae', 'dina.antar@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Domadios', 'Barakat Sedky Mekhael', 'domadios.mekhael@aurak.ac.ae', 'domadios.mekhael@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Eman', 'Shafiq Mohammed Assi', 'eman.assi@aurak.ac.ae', 'eman.assi@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Enjoom', 'Ali Mohammed Sanqoor Al Shehhi', 'enjoom.alshehhi@aurak.ac.ae', 'enjoom.alshehhi@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Esma', 'Erdogan Kilic', 't.esmakilic@aurak.ac.ae', 't.esmakilic@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Faisal', 'Hussein Ali AbdulQader', 'fa.abdulqader@aurak.ac.ae', 'fa.abdulqader@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Fathia', 'Milud M Elmenghawi', 'fathia.elmenghawi@aurak.ac.ae', 'fathia.elmenghawi@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Fayez', 'Moutassem', 'fayez.moutassem@aurak.ac.ae', 'fayez.moutassem@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Gbubemi', 'Haveluck Harrison', 'gbubemi.harrison@aurak.ac.ae', 'gbubemi.harrison@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Ghadah', 'Mohd Al Kadri', 'ghadah.alkadri@aurak.ac.ae', 'ghadah.alkadri@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Gulbahor', 'Amirova', 'g.amirova@aurak.ac.ae', 'g.amirova@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Haifa', 'Ghazi Ibrahim Awad', 'haifa.awad@aurak.ac.ae', 'haifa.awad@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Haileslasie', 'Tadele Gebremariam', 'h.gebremariam@aurak.ac.ae', 'h.gebremariam@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Hamed', 'Assaf', 'hamed.assaf@aurak.ac.ae', 'hamed.assaf@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Hamid', 'Berriche', 'hamid.berriche@aurak.ac.ae', 'hamid.berriche@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Hanan', 'Abdalla Mohamed Elsayed', 'hanan.elsayed@aurak.ac.ae', 'hanan.elsayed@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Hariclea', 'P Zengos', 'hariclea.zengos@aurak.ac.ae', 'hariclea.zengos@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Himankshi', 'Kamlesh Chudasama', 'himankshi.chudasama@aurak.ac.ae', 'himankshi.chudasama@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Hussain', 'Muhammad', 'hussain.muhammad@aurak.ac.ae', 'hussain.muhammad@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Hussain Abdulkarim', 'Al Zouabi', 'hussain.zouabi@aurak.ac.ae', 'hussain.zouabi@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Hussain', 'Abdulridha Attia Thehebawy', 'hattia@aurak.ac.ae', 'hattia@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Hydee', 'Bautista Cenabre', 'HCenabre@aurak.ac.ae', 'HCenabre@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Ibrahim', 'Mohammed Ibrahim Awadallah', 'ibrahim.awadallah@aurak.ac.ae', 'ibrahim.awadallah@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Ilham', 'Mebrouk', 't.ilhammebrouk@aurak.ac.ae', 't.ilhammebrouk@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Inshirah', 'M.S. Shublaq', 'inshirah.shublaq@aurak.ac.ae', 'inshirah.shublaq@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Irene', 'Pasina', 'irene.pasina@aurak.ac.ae', 'irene.pasina@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Irshad', 'Ahmad', 'iahmad@aurak.ac.ae', 'iahmad@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Islam', 'Hassan Abas Alamir', 'islam.alamir@aurak.ac.ae', 'islam.alamir@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Issam', 'Miqdadi', 'issam.miqdadi@aurak.ac.ae', 'issam.miqdadi@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('James', 'Stanley Mall', 'james.mall@aurak.ac.ae', 'james.mall@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('John', 'Marton', 'jmarton@aurak.ac.ae', 'jmarton@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Joseph', 'Lyall Wallis', 'joseph.wallis@aurak.ac.ae', 'joseph.wallis@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Kamel', 'Rabi Mohamed abou El lail mahmoud', 't.kamelmahmoud@aurak.ac.ae', 't.kamelmahmoud@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Kate', 'Louise Moore', 't.katemoore@aurak.ac.ae', 't.katemoore@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Kevin', 'Scott Konecny', 'kevin.konecny@aurak.ac.ae', 'kevin.konecny@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Khaled', 'Abdelgader Mohamed Omar Balawafi', 'khaled.balawafi@aurak.ac.ae', 'khaled.balawafi@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Khaled', 'M. A. Hossin', 'khaled.hossin@aurak.ac.ae', 'khaled.hossin@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Khaleda', 'Yousef Mohammed Almansoori', 'khaleda.almansoori@aurak.ac.ae', 'khaleda.almansoori@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Khalid', 'Hussain', 'khalid.hussain@aurak.ac.ae', 'khalid.hussain@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Khalid', 'Khan', 'khalid.khan@aurak.ac.ae', 'khalid.khan@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Khouloud', 'Joseph Salameh', 'khouloud.salameh@aurak.ac.ae', 'khouloud.salameh@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Kutbettin', 'Kilic', 'kutbettin.kilic@aurak.ac.ae', 'kutbettin.kilic@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Libin', 'Thomas Thomas Kadakketh Thomas', 'libin.thomas@aurak.ac.ae', 'libin.thomas@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Lindsey', 'Janice Kemp', 'lindsey.kemp@aurak.ac.ae', 'lindsey.kemp@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Liudmila', 'Cazacova', 'liudmila.cazacova@aurak.ac.ae', 'liudmila.cazacova@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Liyakhat', 'Ali Khan Mohammed', 'mkhan@aurak.ac.ae', 'mkhan@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Lobna', 'Nassar AB Nassar', 'lobna.nassar@aurak.ac.ae', 'lobna.nassar@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Maen', 'Sadeq Rabah Takruri', 'maen.takruri@aurak.ac.ae', 'maen.takruri@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Maissa', 'Farhat', 'maissa.farhat@aurak.ac.ae', 'maissa.farhat@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Manzoor', 'Kakkatt Abdul Kalam', 'manzoor.kakkatt@aurak.ac.ae', 'manzoor.kakkatt@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Mardy', 'Eserjos Dizon', 't.mardydizon@aurak.ac.ae', 't.mardydizon@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Mayba', 'Fe Chumiwal Bulet', 'mayba.febulet@aurak.ac.ae', 'mayba.febulet@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Micaela', 'Maligalig Castillo', 'micaela.castillo@aurak.ac.ae', 'micaela.castillo@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Mohamad', 'Kharseh', 'mohamad.kharseh@aurak.ac.ae', 'mohamad.kharseh@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Mohamed', 'I Abudakka', 'mohamed.abudakka@aurak.ac.ae', 'mohamed.abudakka@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Mohamed', 'Osman Shereif Mahdi', 'mohamed.mahdi@aurak.ac.ae', 'mohamed.mahdi@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Mohamed', 'Sharul Chundanveettil Pazhaya Ottayil', 'mohamed.sharul@aurak.ac.ae', 'mohamed.sharul@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Mohammad', 'Jamal Issa Azzam', 'mohammad.azzam@aurak.ac.ae', 'mohammad.azzam@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Mohammed', 'Alnahhal', 'mohammed.alnahhal@aurak.ac.ae', 'mohammed.alnahhal@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Mohammed', 'Omari', 'mohammed.omari@aurak.ac.ae', 'mohammed.omari@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Mohammed', 'Abdul Aziz Mohammed Awad', 'mohammed.awad@aurak.ac.ae', 'mohammed.awad@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Mohd', 'Jamal Farid Zaid', 'mohammad.zaid@aurak.ac.ae', 'mohammad.zaid@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Mona', 'Amer Attaya', 't.monaattaya@aurak.ac.ae', 't.monaattaya@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Muataz', 'Hazza', 'muataz.alhazza@aurak.ac.ae', 'muataz.alhazza@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Muhammad', 'Imran Butt', 'muhammad.butt@aurak.ac.ae', 'muhammad.butt@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Muhammad', 'Arshad', 't.muhammadarshad@aurak.ac.ae', 't.muhammadarshad@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Muhammad', 'Shafiq Ahmed', 'muhammad.ahmed@aurak.ac.ae', 'muhammad.ahmed@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Mukdad', 'Mohammad Ibrahim', 'mukdad.ibrahim@aurak.ac.ae', 'mukdad.ibrahim@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Mylene', 'Sadagnot Lacad', 'mylene.lacad@aurak.ac.ae', 'mylene.lacad@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Nafjan', 'Thottathil', 'nafjan.thottathil@aurak.ac.ae', 'nafjan.thottathil@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('NAGESWARA', 'LAKKIMSETTY', 't.nlakkimsetty@aurak.ac.ae', 't.nlakkimsetty@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Nouha', 'Brini', 'nouha.brini@aurak.ac.ae', 'nouha.brini@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Omair', 'Mushtaq Memon Mushtaq Ali Memon', 'omair.memon@aurak.ac.ae', 'omair.memon@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Osama', 'Sohaib', 'osama.sohaib@aurak.ac.ae', 'osama.sohaib@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Paolo', 'Dino Subaldo', 'paolo.subaldo@aurak.ac.ae', 'paolo.subaldo@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Philipp', 'Kaspar Rudolf Dorstewitz', 'philipp.dorstewitz@aurak.ac.ae', 'philipp.dorstewitz@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Rachel', 'Matar', 'rachel.matar@aurak.ac.ae', 'rachel.matar@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Rania', 'Hafiz Hussein Ali', 'rania.ali@aurak.ac.ae', 'rania.ali@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Rashad', 'Vayil Purayil Korembeth', 'rashad.musthafa@aurak.ac.ae', 'rashad.musthafa@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Rawad', 'Hodeify', 'rawad.hodeify@aurak.ac.ae', 'rawad.hodeify@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Rinku', 'Mariam Thomas', 'rinku.thomas@aurak.ac.ae', 'rinku.thomas@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Rowena', 'Mallari Abella', 'rowena.abella@aurak.ac.ae', 'rowena.abella@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('ROZ-UD-DIN', 'Nassar', 'rozuddin.nassar@aurak.ac.ae', 'rozuddin.nassar@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Saad', 'Abdallah Balhassan', 'saad.balhasan@aurak.ac.ae', 'saad.balhasan@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Sabir', 'Haque', 'sabir.haque@aurak.ac.ae', 'sabir.haque@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Salma', 'Musa Abdalla Gargar', 'salma.gargar@aurak.ac.ae', 'salma.gargar@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Sana', 'Tamzini', 't.sanatamzini@aurak.ac.ae', 't.sanatamzini@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Saoussene', 'Osman', 'saoussene.osman@aurak.ac.ae', 'saoussene.osman@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Sara', 'Faiz Hanna Tasfy', 'sara.tasfy@aurak.ac.ae', 'sara.tasfy@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Shadi', 'Yacoub Al Shidrawi', 'shadi.alshidrawi@aurak.ac.ae', 'shadi.alshidrawi@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Shagufta', 'Waseem', 'shagufta.waseem@aurak.ac.ae', 'shagufta.waseem@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Sreejith', 'Cherussery Divakaran', 'sreejith.divakaran@aurak.ac.ae', 'sreejith.divakaran@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Stephen', 'Clark Wilhite', 'stephen.wilhite@aurak.ac.ae', 'stephen.wilhite@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Suleyman', 'Ulusoy', 'suleyman.ulusoy@aurak.ac.ae', 'suleyman.ulusoy@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Suzana', 'Djamtoska Zdravkovska', 'suzana.zdravkovska@aurak.ac.ae', 'suzana.zdravkovska@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Tahseen', 'Anwer Arshi Mohammad Ahsan', 'tahseen.arshi@aurak.ac.ae', 'tahseen.arshi@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Tariq', 'Razzaq Bhatti', 'tariq.bhatti@aurak.ac.ae', 'tariq.bhatti@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Tawfiq', 'Fariz Abuhantash', 'tawfiq.abuhantash@aurak.ac.ae', 'tawfiq.abuhantash@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Tirumala', 'Uday kumar Nutakki', 'uday.kumar@aurak.ac.ae', 'uday.kumar@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Umar', 'Adeel', 'umar.adeel@aurak.ac.ae', 'umar.adeel@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Vazeer Jan', 'Begum', 'vazeerjan.begum@aurak.ac.ae', 'vazeerjan.begum@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Walid', 'Awad El Jammal', 'walid.eljammal@aurak.ac.ae', 'walid.eljammal@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Waseem', 'Ahmed Pallikonda', 'waseem.pallikonda@aurak.ac.ae', 'waseem.pallikonda@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('Wigdan', 'Adil Merghani Hassan', 'wigdan.hassan@aurak.ac.ae', 'wigdan.hassan@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE()),
('ZUBAIDAH', 'ALHAZZA', 't.zubaidahalhazza@aurak.ac.ae', 't.zubaidahalhazza@aurak.ac.ae', 1, 1, 1, GETDATE(), GETDATE());

INSERT INTO UserRole
(UserId, RoleId, Active, ClientId)
SELECT Id, 4, 1, 1 FROM @TABLE
UNION
SELECT Id, 1, 1, 1 FROM @TABLE WHERE mail in ('abeer.almalki@aurak.ac.ae', 'alvin.lumbao@aurak.ac.ae', 'carolyn.ricaplaza@aurak.ac.ae', 'danilo.sangil@aurak.ac.ae', 'domadios.mekhael@aurak.ac.ae', 'libin.thomas@aurak.ac.ae', 'manzoor.kakkatt@aurak.ac.ae', 'mohamed.sharul@aurak.ac.ae', 'nafjan.thottathil@aurak.ac.ae', 'sreejith.divakaran@aurak.ac.ae', 'waseem.pallikonda@aurak.ac.ae')

Update [User]
set Password = hashbytes('sha1', 'ChangeMe1')
WHERE Id in (
	SELECT Id FROM @TABLE
)

COMMIT